# Generated by Django 5.0.9 on 2025-10-17 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='阶段名称')),
                ('description', models.TextField(blank=True, verbose_name='阶段描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='计划开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='计划结束日期')),
                ('status', models.CharField(choices=[('pending', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stages', to=settings.AUTH_USER_MODEL, verbose_name='阶段负责人')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '项目阶段',
                'verbose_name_plural': '项目阶段',
                'ordering': ['order', 'id'],
            },
        ),
    ]
