# Generated by Django 5.0.9 on 2025-10-17 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectstage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '紧急')], default='low', max_length=20, verbose_name='优先级'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', '未开始'), ('in_progress', '进行中'), ('completed', '已完成')], default='not_started', max_length=20, verbose_name='状态'),
        ),
    ]
