# Generated by Django 5.0.9 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('in_progress', '进行中'), ('completed', '已完成')], default='in_progress', max_length=20, verbose_name='状态'),
        ),
    ]
