# Generated by Django 5.0.9 on 2025-10-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectstage_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectstage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectstage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='projectstage',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='截止日期'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='status',
            field=models.CharField(choices=[('in_progress', '进行中'), ('overdue', '已超期'), ('completed', '已完成')], default='in_progress', max_length=20, verbose_name='状态'),
        ),
    ]
