# Generated by Django 5.0.9 on 2025-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_remove_projectstage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='实际完成日期'),
        ),
    ]
